### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Tdzt1** [osantana/staty#3]
Could anybody help fix it. thanks a lot!
when i use pip install staty ,iit comes
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x6tqlpp5/staty/setup.py", line 79
        download_url=f'https://github.com/osantana/staty/tarball/{version}',
                                                                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-x6tqlpp5/staty/

**Comment by mvk07** [comment]
use pip install staty==1.0.0, that will work.
in that package there is a error, /usr/local/lib/python3.5/dist-packages/staty/base.py, line 87
    return f"{self.code} {self.message}"
remove the f. it will work

**Comment by QuenceyTang** [comment]
The syntax f'str' does not work in python < 3.6 .
you can update your python to 3.6+  or change this code to:
'https://github.com/osantana/staty/tarball/{}'.format(version)
And in  that package there is a same problem ,
 /usr/local/lib/python3.5/dist-packages/staty/base.py, line 87 ,
as @mvk07 said,
but it not works just remove f,change it to:
"{0} {1}".format(self.code, self.message)

**Comment by osantana** [comment]
Fixed on version 1.2.4
